# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spelling_bee.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spelling_bee.proto',
  package='game_logic',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12spelling_bee.proto\x12\ngame_logic\"%\n\x11\x43reateGameRequest\x12\x10\n\x08gameType\x18\x01 \x01(\t\"$\n\x12\x43reateGameResponse\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\"9\n\x15RegisterPlayerRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\x12\x10\n\x08userName\x18\x02 \x01(\t\"(\n\x16RegisterPlayerResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\")\n\x17ShowSelectedWordRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\"(\n\x18ShowSelectedWordResponce\x12\x0c\n\x04word\x18\x01 \x01(\t\"`\n\x10\x43heckWordRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\x12\x0c\n\x04word\x18\x02 \x01(\t\".\n\x0eWordMultiplier\x12\t\n\x05\x44UMMY\x10\x00\x12\x11\n\rPANGRAM_BONUS\x10\x07\"3\n\x11\x43heckWordResponse\x12\r\n\x05score\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x13\x43heckRankingRequest\x12\r\n\x05score\x18\x01 \x01(\t\"\'\n\x14\x43heckRankingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb4\x03\n\x08WordGame\x12M\n\nCreateGame\x12\x1d.game_logic.CreateGameRequest\x1a\x1e.game_logic.CreateGameResponse\"\x00\x12Y\n\x0eRegisterPlayer\x12!.game_logic.RegisterPlayerRequest\x1a\".game_logic.RegisterPlayerResponse\"\x00\x12]\n\x10ShowSelectedWord\x12#.game_logic.ShowSelectedWordRequest\x1a$.game_logic.ShowSelectedWordResponce\x12J\n\tCheckWord\x12\x1c.game_logic.CheckWordRequest\x1a\x1d.game_logic.CheckWordResponse\"\x00\x12S\n\x0c\x43heckRanking\x12\x1f.game_logic.CheckRankingRequest\x1a .game_logic.CheckRankingResponse\"\x00\x62\x06proto3'
)



_CHECKWORDREQUEST_WORDMULTIPLIER = _descriptor.EnumDescriptor(
  name='WordMultiplier',
  full_name='game_logic.CheckWordRequest.WordMultiplier',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PANGRAM_BONUS', index=1, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=347,
  serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_CHECKWORDREQUEST_WORDMULTIPLIER)


_CREATEGAMEREQUEST = _descriptor.Descriptor(
  name='CreateGameRequest',
  full_name='game_logic.CreateGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameType', full_name='game_logic.CreateGameRequest.gameType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=71,
)


_CREATEGAMERESPONSE = _descriptor.Descriptor(
  name='CreateGameResponse',
  full_name='game_logic.CreateGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='game_logic.CreateGameResponse.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=109,
)


_REGISTERPLAYERREQUEST = _descriptor.Descriptor(
  name='RegisterPlayerRequest',
  full_name='game_logic.RegisterPlayerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='game_logic.RegisterPlayerRequest.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userName', full_name='game_logic.RegisterPlayerRequest.userName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=168,
)


_REGISTERPLAYERRESPONSE = _descriptor.Descriptor(
  name='RegisterPlayerResponse',
  full_name='game_logic.RegisterPlayerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='game_logic.RegisterPlayerResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=210,
)


_SHOWSELECTEDWORDREQUEST = _descriptor.Descriptor(
  name='ShowSelectedWordRequest',
  full_name='game_logic.ShowSelectedWordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='game_logic.ShowSelectedWordRequest.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=253,
)


_SHOWSELECTEDWORDRESPONCE = _descriptor.Descriptor(
  name='ShowSelectedWordResponce',
  full_name='game_logic.ShowSelectedWordResponce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='game_logic.ShowSelectedWordResponce.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=295,
)


_CHECKWORDREQUEST = _descriptor.Descriptor(
  name='CheckWordRequest',
  full_name='game_logic.CheckWordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='game_logic.CheckWordRequest.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='word', full_name='game_logic.CheckWordRequest.word', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHECKWORDREQUEST_WORDMULTIPLIER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=393,
)


_CHECKWORDRESPONSE = _descriptor.Descriptor(
  name='CheckWordResponse',
  full_name='game_logic.CheckWordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='game_logic.CheckWordResponse.score', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='game_logic.CheckWordResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=446,
)


_CHECKRANKINGREQUEST = _descriptor.Descriptor(
  name='CheckRankingRequest',
  full_name='game_logic.CheckRankingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='game_logic.CheckRankingRequest.score', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=484,
)


_CHECKRANKINGRESPONSE = _descriptor.Descriptor(
  name='CheckRankingResponse',
  full_name='game_logic.CheckRankingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='game_logic.CheckRankingResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=525,
)

_CHECKWORDREQUEST_WORDMULTIPLIER.containing_type = _CHECKWORDREQUEST
DESCRIPTOR.message_types_by_name['CreateGameRequest'] = _CREATEGAMEREQUEST
DESCRIPTOR.message_types_by_name['CreateGameResponse'] = _CREATEGAMERESPONSE
DESCRIPTOR.message_types_by_name['RegisterPlayerRequest'] = _REGISTERPLAYERREQUEST
DESCRIPTOR.message_types_by_name['RegisterPlayerResponse'] = _REGISTERPLAYERRESPONSE
DESCRIPTOR.message_types_by_name['ShowSelectedWordRequest'] = _SHOWSELECTEDWORDREQUEST
DESCRIPTOR.message_types_by_name['ShowSelectedWordResponce'] = _SHOWSELECTEDWORDRESPONCE
DESCRIPTOR.message_types_by_name['CheckWordRequest'] = _CHECKWORDREQUEST
DESCRIPTOR.message_types_by_name['CheckWordResponse'] = _CHECKWORDRESPONSE
DESCRIPTOR.message_types_by_name['CheckRankingRequest'] = _CHECKRANKINGREQUEST
DESCRIPTOR.message_types_by_name['CheckRankingResponse'] = _CHECKRANKINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateGameRequest = _reflection.GeneratedProtocolMessageType('CreateGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMEREQUEST,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.CreateGameRequest)
  })
_sym_db.RegisterMessage(CreateGameRequest)

CreateGameResponse = _reflection.GeneratedProtocolMessageType('CreateGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMERESPONSE,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.CreateGameResponse)
  })
_sym_db.RegisterMessage(CreateGameResponse)

RegisterPlayerRequest = _reflection.GeneratedProtocolMessageType('RegisterPlayerRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERPLAYERREQUEST,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.RegisterPlayerRequest)
  })
_sym_db.RegisterMessage(RegisterPlayerRequest)

RegisterPlayerResponse = _reflection.GeneratedProtocolMessageType('RegisterPlayerResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERPLAYERRESPONSE,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.RegisterPlayerResponse)
  })
_sym_db.RegisterMessage(RegisterPlayerResponse)

ShowSelectedWordRequest = _reflection.GeneratedProtocolMessageType('ShowSelectedWordRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOWSELECTEDWORDREQUEST,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.ShowSelectedWordRequest)
  })
_sym_db.RegisterMessage(ShowSelectedWordRequest)

ShowSelectedWordResponce = _reflection.GeneratedProtocolMessageType('ShowSelectedWordResponce', (_message.Message,), {
  'DESCRIPTOR' : _SHOWSELECTEDWORDRESPONCE,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.ShowSelectedWordResponce)
  })
_sym_db.RegisterMessage(ShowSelectedWordResponce)

CheckWordRequest = _reflection.GeneratedProtocolMessageType('CheckWordRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKWORDREQUEST,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.CheckWordRequest)
  })
_sym_db.RegisterMessage(CheckWordRequest)

CheckWordResponse = _reflection.GeneratedProtocolMessageType('CheckWordResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKWORDRESPONSE,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.CheckWordResponse)
  })
_sym_db.RegisterMessage(CheckWordResponse)

CheckRankingRequest = _reflection.GeneratedProtocolMessageType('CheckRankingRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKRANKINGREQUEST,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.CheckRankingRequest)
  })
_sym_db.RegisterMessage(CheckRankingRequest)

CheckRankingResponse = _reflection.GeneratedProtocolMessageType('CheckRankingResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKRANKINGRESPONSE,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:game_logic.CheckRankingResponse)
  })
_sym_db.RegisterMessage(CheckRankingResponse)



_WORDGAME = _descriptor.ServiceDescriptor(
  name='WordGame',
  full_name='game_logic.WordGame',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=528,
  serialized_end=964,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateGame',
    full_name='game_logic.WordGame.CreateGame',
    index=0,
    containing_service=None,
    input_type=_CREATEGAMEREQUEST,
    output_type=_CREATEGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterPlayer',
    full_name='game_logic.WordGame.RegisterPlayer',
    index=1,
    containing_service=None,
    input_type=_REGISTERPLAYERREQUEST,
    output_type=_REGISTERPLAYERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ShowSelectedWord',
    full_name='game_logic.WordGame.ShowSelectedWord',
    index=2,
    containing_service=None,
    input_type=_SHOWSELECTEDWORDREQUEST,
    output_type=_SHOWSELECTEDWORDRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckWord',
    full_name='game_logic.WordGame.CheckWord',
    index=3,
    containing_service=None,
    input_type=_CHECKWORDREQUEST,
    output_type=_CHECKWORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckRanking',
    full_name='game_logic.WordGame.CheckRanking',
    index=4,
    containing_service=None,
    input_type=_CHECKRANKINGREQUEST,
    output_type=_CHECKRANKINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORDGAME)

DESCRIPTOR.services_by_name['WordGame'] = _WORDGAME

# @@protoc_insertion_point(module_scope)
